"""Initial migration

Revision ID: 44a2381228ed
Revises:
Create Date: 2025-09-24 18:14:45.880362

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "44a2381228ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
